services:
  xray:
    image: ghcr.io/xtls/xray-core:26.1.13
    container_name: xray
    restart: always
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config:/usr/local/etc/xray